on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build Next.js project
        run: npm run build

      - name: Run tests
        env:
          DATABASE_URL_AUTH: "postgresql://auth_admin:dbpass@localhost:5432/auth_db"
          DATABASE_URL_APP: "postgresql://app_admin:apppassword@localhost:5432/app_db"
          NEXTAUTH_SECRET: "supersecretkey"
          NEXT_PUBLIC_BACKEND_URL: "http://localhost:8000"
          NEXT_PUBLIC_AUTH_URL: "http://localhost:8001"
          NEXT_PUBLIC_APP_URL: "http://localhost:8002"
          NEXTAUTH_JWT_ENCRYPTION: "false"
          NEXTAUTH_URL: "http://localhost:3000"
        run: npm test
